
services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    image: money_transfer_app
    container_name: money_transfer_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./backend:/var/www
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: money_transfer_nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./backend:/var/www
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - app
    networks:
      - app-network

  db:
    image: mysql:8.0
    container_name: money_transfer_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: money_transfer
      MYSQL_ROOT_PASSWORD: password
      MYSQL_PASSWORD: password
      MYSQL_USER: user
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - app-network

  redis:
    image: redis:alpine
    container_name: money_transfer_redis
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
