"A datetime string with format 'Y-m-d H:i:s', e.g. '2018-05-23 13:43:32'."
scalar DateTime @scalar(class: "Nuwave\\Lighthouse\\Schema\\Types\\Scalars\\DateTime")

type Query {
    users: [User!]! @all
    user(id: ID @eq): User @find
    
    clients: [Client!]! @all
    client(id: ID @eq): Client @find

    transactions: [Transaction!]! @all
    transaction(id: ID @eq): Transaction @find

    wallets: [Wallet!]! @all
    
    countries: [Country!]! @all
    country(id: ID @eq): Country @find
}

type Country {
    id: ID!
    name: String!
    code: String!
    currency: String!
    phone_code: String!
    created_at: DateTime!
    updated_at: DateTime!
}

type User {
    id: ID!
    name: String!
    email: String!
    created_at: DateTime!
    updated_at: DateTime!
    wallet: Wallet @hasOne
}

type Client {
    id: ID!
    name: String!
    phone: String!
    created_at: DateTime!
    updated_at: DateTime!
    transactions: [Transaction!]! @hasMany
}

type Wallet {
    id: ID!
    uuid: String!
    balance: Float!
    currency: String!
    user: User @belongsTo
}

type Transaction {
    id: ID!
    uuid: String!
    amount: Float!
    currency: String!
    status: String!
    type: String!
    reference: String
    created_at: DateTime!
    sender_wallet: Wallet @belongsTo(relation: "senderWallet")
    payout_wallet: Wallet @belongsTo(relation: "payoutWallet")
    client: Client @belongsTo
}
